# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

      # Runs a set of commands using the runners shell
      - name: Poetry update
        run: $HOME/.poetry/bin/poetry update
        working-directory: $GITHUB_WORKSPACE
        
      - name: Maturin release
        run: $HOME/.poetry/bin/poetry run maturin build release
        working-directory: $GITHUB_WORKSPACE
        
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: $GITHUB_WORKSPACE/target/wheels
